[package]
name = "gftopdf"
version = "2.0.0"
authors = ["Don Hosek <don.hosek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
thiserror = "1.0"
